### ISSUE TITLE
ccapurroroy tracks progress on GitHub Flow

### ISSUE THREAD

**Issue by ccapurroroy** [githubteacher/july-11-for-developers#7]
- [ ] create a branch off of master
- [ ] add a commit
- [ ] open a pull request (PR) 
- [ ] have a conversion
- [ ] add additional commits
- [ ] merge after receiving :+1:

**Comment by michaelmsinclair** [comment]
Hey, I can tick your checklist.

**Comment by michaelmsinclair** [comment]
And now I've unchecked it.
